version: '3'

services:
  django:
    build:
      context: .
      dockerfile: deploy/Dockerfile-django
    env_file: run/scionlab.env
    expose:
      - "8000"
    volumes:
      - ./run/:/scionlab/run/:z
      - web-static:/scionlab/static/:z

  caddy:
    build: ./deploy/caddy
    env_file: run/scionlab.env
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-static:/var/www/scionlab/static:z
      - caddydata:/home/caddy/.caddy/:Z

volumes:
  web-static:
  redisdata:
  caddydata:
